name: Update README

on:
  schedule:
    - cron: '30 2,10,18 * * *' 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          
      - name: Update README.md
        env:
          # Use your PAT or the default GH_TOKEN
          GH_TOKEN: ${{ secrets.METRICS_TOKEN }}
        run: python .github/scripts/update_readme.py
        
      - name: Commit and Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md github-metrics-dark.svg github-metrics-light.svg
          git commit -m 'chore: dynamically update README stats and SVG' || echo "No changes to commit"
          git push
